/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Persistence;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ncahy
 */
public class Uts extends javax.swing.JFrame {

    private final String[] columns = {"kode_mk", "sks", "nama_mk", "semester_ajar"};
    private final ArrayList<String[]> dataList = new ArrayList<>();
    Connection conn;
    Matakuliah matakuliah = new Matakuliah();
    static EntityManagerFactory emf = Persistence.createEntityManagerFactory("cobaCrudPU");
    EntityManager em = emf.createEntityManager();

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/pboUTS";
    String user = "postgres";
    String password = "codotganteng";

//    public final void getAllData() {
//        try {
//            dataList.clear();
//            String sql = "SELECT * FROM matakuliah order by kode_mk asc";
//            conn = DriverManager.getConnection(koneksi, user, password);
//            PreparedStatement ps = conn.prepareStatement(sql);
//            ps.executeQuery();
//            final ResultSet data = ps.getResultSet();
//            while (data.next()) {
//                final String[] row = new String[]{
//                    data.getString("kode_mk"),
//                    data.getString("sks"),
//                    data.getString("nama_mk"),
//                    data.getString("semester_ajar")};
//                dataList.add(row);
//            }
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    }
    
    public void tampilPU() {
        em = emf.createEntityManager();

        try {
            // Buat model tabel dengan kolom yang sesuai
            DefaultTableModel tbnmhs = new DefaultTableModel(new String[]{"kode_mk", "sks", "nama_mk", "semester_ajar"}, 0);

            // Menggunakan NamedQuery "Matakuliah.findAll" untuk mengambil semua data
            List<Matakuliah> mataKuliahList = em.createNamedQuery("Matakuliah.findAll", Matakuliah.class).getResultList();

            // Iterasi hasil query dan tambahkan baris ke model tabel
            for (Matakuliah matakuliah : mataKuliahList) {
                tbnmhs.addRow(new Object[]{
                    matakuliah.getKodeMk(),
                    matakuliah.getSks(),
                    matakuliah.getNamaMk(),
                    matakuliah.getSemesterAjar()
                });
            }

            // Atur model tabel ke tabel GUI
            Table.setModel(tbnmhs);
        } catch (Exception ex) {
        }
    }

    

    /**
     * Creates new form Uts
     */
    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        for (String[] data : dataList) {
            model.addRow(data);
        }
        Table.setModel(model);
    }

    public Uts() {
        initComponents();
        Bupdate.setEnabled(false);
        tampilPU();
        try{
            conn=DriverManager.getConnection(koneksi, user, password);
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFkode = new javax.swing.JTextField();
        TFsks = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        TFsemester = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Binsert = new javax.swing.JButton();
        Bdelete = new javax.swing.JButton();
        Bclear = new javax.swing.JButton();
        Bupdate = new javax.swing.JButton();
        Bcetak = new javax.swing.JButton();
        Bupload = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("MATA KULIAH");

        jLabel2.setText("KodeMK");

        jLabel3.setText("SKS");

        jLabel4.setText("NamaMK");

        jLabel5.setText("SemesterAjar");

        TFkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFkodeActionPerformed(evt);
            }
        });

        TFsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsksActionPerformed(evt);
            }
        });

        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });

        TFsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsemesterActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        Binsert.setText("INSERT");
        Binsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinsertActionPerformed(evt);
            }
        });

        Bdelete.setText("DELETE");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });

        Bclear.setText("CLEAR");
        Bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclearActionPerformed(evt);
            }
        });

        Bupdate.setText("UPDATE");
        Bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupdateActionPerformed(evt);
            }
        });

        Bcetak.setText("CETAK");
        Bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcetakActionPerformed(evt);
            }
        });

        Bupload.setText("UPLOAD");
        Bupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Binsert, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFkode)
                            .addComponent(TFsks)
                            .addComponent(TFnama)
                            .addComponent(TFsemester, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bdelete)
                                .addGap(18, 18, 18)
                                .addComponent(Bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bupdate)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bupload)
                        .addGap(18, 18, 18)
                        .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFsks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Binsert)
                    .addComponent(Bdelete)
                    .addComponent(Bclear)
                    .addComponent(Bupdate))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcetak)
                    .addComponent(Bupload))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinsertActionPerformed
        // TODO add your handling code here:
        String KodeMK = TFkode.getText();
        String SKS = TFsks.getText();
        String NamaMK = TFnama.getText();
        String SemesterAjar = TFsemester.getText();
        if (KodeMK.trim().isEmpty() && SKS.trim().isEmpty() && NamaMK.trim().isEmpty() && SemesterAjar.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan data anda");

        } else if (KodeMK.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan kodeMK");
        } else if (SKS.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan Jumlah SKS");
        } else if (NamaMK.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan NamaMK");
        } else if (SemesterAjar.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan SemesterAjar");
        } else {
            em.getTransaction().begin();
            matakuliah.setKodeMk(TFkode.getText());
            matakuliah.setNamaMk(TFnama.getText());
            matakuliah.setSemesterAjar(TFsemester.getText());
            matakuliah.setSks(TFsks.getText());
            em.persist(matakuliah);
            em.getTransaction().commit();
            tampilPU();

                Bupdate.setEnabled(false);
                TFkode.setEditable(true);
                JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");

            }
    }//GEN-LAST:event_BinsertActionPerformed

    private void TFkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFkodeActionPerformed

    private void TFsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsksActionPerformed

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void TFsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsemesterActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed
        // TODO add your handling code here:
        String kode_mk = TFkode.getText();
        if (kode_mk.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error ngab", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            em.getTransaction().begin();

            matakuliah = em.find(Matakuliah.class, TFkode.getText());
            em.remove(matakuliah);
            em.getTransaction().commit();
            
            tampilPU();
        }
    }//GEN-LAST:event_BdeleteActionPerformed

    private void BupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupdateActionPerformed
        // TODO add your handling code here:
        em.getTransaction().begin();

            matakuliah = em.find(Matakuliah.class, TFkode.getText());

            matakuliah.setKodeMk(TFkode.getText());
            matakuliah.setNamaMk(TFnama.getText());
            matakuliah.setSemesterAjar(TFsemester.getText());
            matakuliah.setSks(TFsks.getText());
            em.persist(matakuliah);
            em.getTransaction().commit();
            
            tampilPU();
    }//GEN-LAST:event_BupdateActionPerformed

    private void BclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclearActionPerformed
        // TODO add your handling code here:
        TFkode.setText("");
        TFsks.setText("");
        TFnama.setText("");
        TFsemester.setText("");
        Bupdate.setEnabled(false);
        TFkode.setEditable(true);
    }//GEN-LAST:event_BclearActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int selectedRow = Table.getSelectedRow();
        if (selectedRow != -1) {
            String kode_mk = Table.getValueAt(selectedRow, 0).toString();
            String sks = Table.getValueAt(selectedRow, 1).toString();
            String nama_mk = Table.getValueAt(selectedRow, 2).toString();
            String semester_ajar = Table.getValueAt(selectedRow, 3).toString();

            TFkode.setText(kode_mk);
            TFsks.setText(sks);
            TFnama.setText(nama_mk);
            TFsemester.setText(semester_ajar);
            Bupdate.setEnabled(true);
            TFkode.setEditable(false);
        }
    }//GEN-LAST:event_TableMouseClicked

    private void BcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcetakActionPerformed
        // TODO add your handling code here:
        try {
            JasperReport reports;
            String path = "src\\Persistance\\report1.jasper";
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint print = JasperFillManager.fillReport(path, null, conn);
            JasperViewer view = new JasperViewer(print, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);

        } catch (JRException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BcetakActionPerformed

    private void BuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());
            try {
                BufferedReader br = new BufferedReader(new FileReader(filePilihan));
                String baris = new String("");
                String pemisah = ",";
                while ((baris = br.readLine()) != null) //returns a Boolean value
                {
                    String[] dataMhs = baris.split(pemisah);
                    String kodeMk = dataMhs[0];
                    String sks = dataMhs[1];
                    String namaMK = dataMhs[2];
                    String semester = dataMhs[3];

                    if (!kodeMk.isEmpty() && !sks.isEmpty() && !namaMK.isEmpty() && !semester.isEmpty()) {
                        em.getTransaction().begin();
                        matakuliah.setKodeMk(kodeMk);
                        matakuliah.setNamaMk(namaMK);
                        matakuliah.setSemesterAjar(semester);
                        matakuliah.setSks(sks);
                        em.persist(matakuliah);
                        em.getTransaction().commit();
                        JOptionPane.showMessageDialog(this, "data berhasil ditambahkan");
                        
                tampilPU();
//                        showAll();
//                        this.refreshModel();
                    }
                }
            } catch (FileNotFoundException ex) {
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_BuploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcetak;
    private javax.swing.JButton Bclear;
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Binsert;
    private javax.swing.JButton Bupdate;
    private javax.swing.JButton Bupload;
    private javax.swing.JTextField TFkode;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFsemester;
    private javax.swing.JTextField TFsks;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
